### ISSUE TITLE
This project is incompatible with Python < 3.11

### ISSUE THREAD

**Issue by duncanmmacleod** [conda-forge/rattler-build-conda-compat-feedstock#11]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

This project is incompatible with Python 3.11, as reported at https://github.com/nichmor/rattler-build-conda-compat/issues/19, this results in issues downstream for conda-forge feedstock builds:

```pytb
+ setup_conda_rc ./ ./recipe ./.ci_support/osx_64_.yaml


Setting up the condarc and mangling the compiler.
Traceback (most recent call last):
  File "/Users/runner/miniforge3/bin/setup_conda_rc", line 7, in <module>
    from conda_forge_ci_setup.build_utils import setup_conda_rc
  File "/Users/runner/miniforge3/lib/python3.10/site-packages/conda_forge_ci_setup/build_utils.py", line 15, in <module>
    from conda_forge_ci_setup.upload_or_check_non_existence import retry_upload_or_check
  File "/Users/runner/miniforge3/lib/python3.10/site-packages/conda_forge_ci_setup/upload_or_check_non_existence.py", line 18, in <module>
    import rattler_build_conda_compat.render
  File "/Users/runner/miniforge3/lib/python3.10/site-packages/rattler_build_conda_compat/render.py", line 23, in <module>
    from rattler_build_conda_compat.loader import parse_recipe_config_file
  File "/Users/runner/miniforge3/lib/python3.10/site-packages/rattler_build_conda_compat/loader.py", line 4, in <module>
    from typing import TYPE_CHECKING, Any, Iterator, Self
ImportError: cannot import name 'Self' from 'typing' (/Users/runner/miniforge3/lib/python3.10/typing.py)
```

Can the feedstock bump itself to require `python >=3.11` (at least at runtime).

See, e.g: https://github.com/conda-forge/lalburst-feedstock/runs/27616146302

### Installed packages

```shell
-
```

### Environment info

```shell
-
```

**Comment by baszalmstra** [comment]
Sorry for the inconvenience! We fixed the issue upstream and are in the process of releasing.

**Comment by baszalmstra** [comment]
The broken version has been marked as broken we will release a new version today (#16 ) where this issue is resolved and has tests in place to ensure it keeps working..

**Comment by baszalmstra** [comment]
`v0.2.1` has been released which fixes this issue.
